# Generated by Django 4.0.6 on 2022-09-10 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import workshop_data.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDetailInPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_batch', models.SmallIntegerField(default=0, verbose_name='Колличество в партии')),
                ('sos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Деталь')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.categorydetail', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Изделие')),
                ('detail', models.ManyToManyField(blank=True, related_name='product', to='workshop_data.detail', verbose_name='Деталь')),
            ],
        ),
        migrations.CreateModel(
            name='StageManufacturingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(choices=[('LSM', 'Слесарый'), ('TRN', 'Токарный'), ('MLR', 'Фрезеровальный'), ('GRN', 'Шлифовальный')], max_length=3)),
                ('operations', models.CharField(max_length=300)),
                ('normalized_time', models.FloatField(default=0, verbose_name='Нормированное время')),
                ('price', models.FloatField(default=0, verbose_name='Расценка')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.detail')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0, verbose_name='Колличество')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь'), (13, 'не укзан')], default=13, verbose_name='_Месяц_')),
                ('sos', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2022), workshop_data.models.max_value_current_year])),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop_data.batchdetailinplan', verbose_name='_Партия_')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.detail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.product', verbose_name='_Изделие_')),
            ],
        ),
        migrations.CreateModel(
            name='StageManufacturingDetailInWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_work', models.DateTimeField()),
                ('time_of_work', models.SmallIntegerField()),
                ('comment_in_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.comment')),
                ('stage_in_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.stagemanufacturingdetail')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Рабочий')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь'), (13, 'не укзан')], default=13, verbose_name='Месяц')),
                ('workshop', models.PositiveSmallIntegerField(default=464)),
                ('section', models.PositiveSmallIntegerField(default=1)),
                ('employee_number', models.PositiveSmallIntegerField()),
                ('operations', models.TextField(verbose_name='Операции')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Колличесво')),
                ('normalized_time', models.FloatField(default=0, verbose_name='Нормированное время')),
                ('price', models.FloatField(default=0, verbose_name='Расценка')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.detail', verbose_name='Деталь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.product', verbose_name='Изделие')),
                ('surname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Рабочий')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Узел')),
                ('detail', models.ManyToManyField(related_name='node', to='workshop_data.detail')),
                ('product', models.ManyToManyField(related_name='node', to='workshop_data.product')),
            ],
        ),
        migrations.AddField(
            model_name='batchdetailinplan',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.comment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='batchdetailinplan',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.stagemanufacturingdetailinwork', verbose_name='Этап изготовления'),
        ),
    ]
