# Generated by Django 4.0.6 on 2023-01-19 16:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import workshop_data.services.general_services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDetailInPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_batch', models.SmallIntegerField(default=0, verbose_name='Количество в партии')),
                ('ready', models.BooleanField(default=False)),
                ('sos', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_batch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
            },
        ),
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Деталь')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.categorydetail', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Изделие')),
                ('detail', models.ManyToManyField(blank=True, related_name='product', to='workshop_data.detail', verbose_name='Деталь')),
            ],
        ),
        migrations.CreateModel(
            name='StageManufacturingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='Порядок')),
                ('name', models.CharField(choices=[('', 'Выберите вид работы'), ('LSM', 'Слесарый'), ('TRN', 'Токарный'), ('MLR', 'Фрезеровальный'), ('GRN', 'Шлифовальный')], max_length=3, verbose_name='Вид работы')),
                ('operations', models.CharField(max_length=300, unique=True, verbose_name='Операции')),
                ('normalized_time', models.FloatField(default=0, verbose_name='Нормированное время')),
                ('price', models.FloatField(default=0, verbose_name='Расценка')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='workshop_data.detail', verbose_name='Деталь')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_state_order', models.PositiveSmallIntegerField(default=0, verbose_name='Госзаказ')),
                ('quantity_commercial_order', models.PositiveSmallIntegerField(default=0, verbose_name='Коммерция')),
                ('in_work', models.PositiveSmallIntegerField(default=0, verbose_name='Количество в работе')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь'), (13, 'не указан')], default=13, verbose_name='Месяц')),
                ('sos', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2022), workshop_data.services.general_services.max_value_current_year])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_workshopplan', to=settings.AUTH_USER_MODEL)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.detail', verbose_name='Деталь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.product', verbose_name='Изделие')),
            ],
        ),
        migrations.CreateModel(
            name='StatementAboutJobOverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_statement', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.detail', verbose_name='Деталь')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Рабочий')),
            ],
        ),
        migrations.CreateModel(
            name='StageManufacturingDetailInWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_work', models.DateTimeField(auto_now_add=True)),
                ('in_work', models.BooleanField(default=False, verbose_name='В работе')),
                ('job_is_done', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_stage_in_work', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='workshop_data.batchdetailinplan', verbose_name='Партия')),
                ('comment_in_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.comment', verbose_name='Комментарий')),
                ('stage_in_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.stagemanufacturingdetail', verbose_name='Этап')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Рабочий')),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionForStatementAboutJobOverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.BooleanField(default=False)),
                ('date_approval', models.DateTimeField(blank=True, default=None, null=True)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolute', to='workshop_data.statementaboutjoboverdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь'), (13, 'не указан')], default=13, verbose_name='Месяц')),
                ('workshop', models.PositiveSmallIntegerField(default=464)),
                ('section', models.PositiveSmallIntegerField(default=1)),
                ('employee_number', models.PositiveSmallIntegerField()),
                ('operations', models.TextField(verbose_name='Операции')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('normalized_time', models.FloatField(default=0, verbose_name='Нормированное время')),
                ('price', models.FloatField(default=0, verbose_name='Расценка')),
                ('time_of_work_order', models.SmallIntegerField(blank=True, default=0, verbose_name='Затраченное время')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_order', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.batchdetailinplan', verbose_name='Партия')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.detail', verbose_name='Деталь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.product', verbose_name='Изделие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Рабочий')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Узел')),
                ('detail', models.ManyToManyField(related_name='node', to='workshop_data.detail')),
                ('product', models.ManyToManyField(related_name='node', to='workshop_data.product')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.prefix'),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0, verbose_name='Сумма')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь'), (13, 'не указан')], default=13, verbose_name='Месяц')),
                ('time', models.SmallIntegerField(default=0, verbose_name='Затраченное время')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_bonus', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.comment', verbose_name='Комментарий')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_bonus', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
        ),
        migrations.AddField(
            model_name='batchdetailinplan',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.comment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='batchdetailinplan',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batchs', to='workshop_data.detail', verbose_name='Деталь'),
        ),
        migrations.AddField(
            model_name='batchdetailinplan',
            name='workshopplan_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batchs', to='workshop_data.workshopplan'),
        ),
    ]
