# Generated by Django 4.0.6 on 2022-11-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='surname',
            new_name='user',
        ),
    ]
