# Generated by Django 4.0.6 on 2022-07-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь'), (13, 'не укзан')], default=13, max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.detail', verbose_name='Деталь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='normalized_time',
            field=models.FloatField(default=0, verbose_name='Нормированное время'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operations',
            field=models.TextField(verbose_name='Операции'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0, verbose_name='Расценка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.product', verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Колличесво'),
        ),
        migrations.AlterField(
            model_name='order',
            name='section',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='workshop',
            field=models.PositiveSmallIntegerField(default=464),
        ),
    ]
