# Generated by Django 4.0.6 on 2023-02-20 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_in_order', to='workshop_data.stagemanufacturingdetail', verbose_name='Этап'),
        ),
    ]
