# Generated by Django 4.0.6 on 2022-09-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopplan',
            name='batch',
        ),
    ]
