# Generated by Django 4.0.6 on 2022-09-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydetail',
            name='detail',
        ),
        migrations.AddField(
            model_name='detail',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.categorydetail', verbose_name='Категория'),
        ),
    ]
