# Generated by Django 4.0.6 on 2022-09-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0002_remove_workshopplan_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopplan',
            name='in_work',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Колличество в работе'),
        ),
        migrations.AlterField(
            model_name='workshopplan',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Колличество'),
        ),
    ]
