# Generated by Django 4.0.6 on 2022-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0002_categorydetail_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Деталь'),
        ),
    ]
