# Generated by Django 4.0.6 on 2022-11-01 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0002_comment_author_order_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetailinplan',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='uesr_batch', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
