# Generated by Django 4.0.6 on 2023-01-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0002_alter_node_detail_alter_node_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='node',
            field=models.ManyToManyField(blank=True, related_name='product', to='workshop_data.node', verbose_name='Узел'),
        ),
    ]
