# Generated by Django 4.0.6 on 2022-07-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0002_order_month_alter_order_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь'), (13, 'не укзан')], default=13),
        ),
    ]
