# Generated by Django 4.0.6 on 2022-09-18 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0002_remove_categorydetail_detail_detail_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchdetailinplan',
            name='detail',
        ),
        migrations.AddField(
            model_name='workshopplan',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.batchdetailinplan', verbose_name='_Партия_'),
        ),
    ]
