# Generated by Django 4.0.6 on 2022-11-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0003_rename_time_of_work_stagemanufacturingdetailinwork_time_of_work_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_of_work',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Затраченное время'),
        ),
    ]
