# Generated by Django 4.0.6 on 2022-11-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0003_batchdetailinplan_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemanufacturingdetailinwork',
            name='job_is_done',
            field=models.BooleanField(default=False),
        ),
    ]
