# Generated by Django 4.0.6 on 2023-01-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0003_remove_node_product_product_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node',
            field=models.ManyToManyField(blank=True, related_name='node_within_node', to='workshop_data.node'),
        ),
    ]
