# Generated by Django 4.0.6 on 2022-12-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0003_alter_detail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetailinplan',
            name='detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='batchs', to='workshop_data.detail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchdetailinplan',
            name='quantity_in_batch',
            field=models.SmallIntegerField(default=0, verbose_name='Количество в партии'),
        ),
    ]
