# Generated by Django 4.0.6 on 2022-09-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0003_remove_batchdetailinplan_detail_workshopplan_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopplan',
            name='batch',
        ),
        migrations.AddField(
            model_name='batchdetailinplan',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.workshopplan'),
        ),
    ]
