# Generated by Django 4.0.6 on 2022-07-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0003_alter_order_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь'), (13, 'не укзан')], default=13, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='order',
            name='section',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
