# Generated by Django 4.0.6 on 2022-09-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0004_batchdetailinplan_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.detail', verbose_name='Деталь'),
        ),
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='name',
            field=models.CharField(choices=[('LSM', 'Слесарый'), ('TRN', 'Токарный'), ('MLR', 'Фрезеровальный'), ('GRN', 'Шлифовальный')], default='Выберите вид работы', max_length=3, verbose_name='Вид работы'),
        ),
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='operations',
            field=models.CharField(max_length=300, verbose_name='Операции'),
        ),
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Порядок'),
        ),
    ]
