# Generated by Django 4.0.6 on 2022-07-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0004_alter_order_month_alter_order_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.categorydetail', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Деталь'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Изделие'),
        ),
    ]
