# Generated by Django 4.0.6 on 2022-12-20 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0004_batchdetailinplan_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdetailinplan',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batchs', to='workshop_data.detail', verbose_name='Деталь'),
        ),
        migrations.AlterField(
            model_name='categorydetail',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='workshopplan',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.detail', verbose_name='Деталь'),
        ),
        migrations.CreateModel(
            name='StatementAboutJobOverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_statement', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.detail', verbose_name='Деталь')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Рабочий')),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionForStatementAboutJobOverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.BooleanField(default=False)),
                ('date_approval', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.comment', verbose_name='Комментарий')),
                ('master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
        ),
    ]
