# Generated by Django 4.0.6 on 2023-03-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.prefix'),
        ),
    ]
