# Generated by Django 4.0.6 on 2022-09-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0004_remove_workshopplan_batch_batchdetailinplan_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopplan',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.detail'),
        ),
        migrations.AlterField(
            model_name='workshopplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.product', verbose_name='_Изделие_'),
        ),
    ]
