# Generated by Django 4.0.6 on 2022-11-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0004_order_time_of_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time_of_work',
            new_name='time_of_work_order',
        ),
    ]
