# Generated by Django 4.0.6 on 2023-01-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0004_node_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.prefix'),
        ),
    ]
