# Generated by Django 4.0.6 on 2022-12-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0005_alter_batchdetailinplan_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolutionforstatementaboutjoboverdetail',
            name='statement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.statementaboutjoboverdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statementaboutjoboverdetail',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.detail', unique=True, verbose_name='Деталь'),
        ),
    ]
