# Generated by Django 4.0.6 on 2022-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0005_alter_stagemanufacturingdetail_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='name',
            field=models.CharField(choices=[('LSM', 'Слесарый'), ('TRN', 'Токарный'), ('MLR', 'Фрезеровальный'), ('GRN', 'Шлифовальный')], default='LSM', max_length=3, verbose_name='Вид работы'),
        ),
    ]
