# Generated by Django 4.0.6 on 2023-01-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0005_node_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='category',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.categorydetail'),
            preserve_default=False,
        ),
    ]
