# Generated by Django 4.0.6 on 2022-12-01 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0005_rename_time_of_work_order_time_of_work_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0, verbose_name='Колличество')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_bonus', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.comment', verbose_name='Комментарий')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_bonus', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
        ),
    ]
