# Generated by Django 4.0.6 on 2022-09-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0006_alter_stagemanufacturingdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='name',
            field=models.CharField(choices=[('', 'Выберите вид работы'), ('LSM', 'Слесарый'), ('TRN', 'Токарный'), ('MLR', 'Фрезеровальный'), ('GRN', 'Шлифовальный')], max_length=3, verbose_name='Вид работы'),
        ),
    ]
