# Generated by Django 4.0.6 on 2022-09-24 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0006_alter_stagemanufacturingdetailinwork_stage_in_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Рабочий'),
        ),
    ]
