# Generated by Django 4.0.6 on 2023-03-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0006_alter_order_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='batch',
        ),
    ]
