# Generated by Django 4.0.6 on 2022-12-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0006_resolutionforstatementaboutjoboverdetail_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionforstatementaboutjoboverdetail',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.comment', verbose_name='Комментарий'),
        ),
    ]
