# Generated by Django 4.0.6 on 2022-12-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0006_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='time',
            field=models.SmallIntegerField(default=0, verbose_name='Затраченное время'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='quantity',
            field=models.SmallIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
