# Generated by Django 4.0.6 on 2022-08-27 15:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import workshop_data.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0006_product_detail_alter_order_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDetailInPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailInPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0, verbose_name='Колличество')),
                ('quantity_batch', models.SmallIntegerField(default=1, verbose_name='_Партия_')),
                ('sos', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_in_plan', to='workshop_data.batchdetailinplan')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.detail', verbose_name='_Деталь_')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='workshop_data.detailinplan')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.ManyToManyField(blank=True, related_name='product', to='workshop_data.detail', verbose_name='Деталь'),
        ),
        migrations.CreateModel(
            name='WorkshopPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь'), (13, 'не укзан')], default=13, verbose_name='_Месяц_')),
                ('year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2022), workshop_data.models.max_value_current_year])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.productinplan')),
            ],
        ),
        migrations.AddField(
            model_name='productinplan',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.product', verbose_name='_Изделие_'),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Узел')),
                ('detail', models.ManyToManyField(related_name='node', to='workshop_data.detail')),
                ('product', models.ManyToManyField(related_name='node', to='workshop_data.product')),
            ],
        ),
        migrations.AddField(
            model_name='batchdetailinplan',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.comment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='batchdetailinplan',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Рабочий'),
        ),
    ]
