# Generated by Django 4.0.6 on 2022-12-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0007_bonus_time_alter_bonus_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь'), (13, 'не указан')], default=13, verbose_name='Месяц'),
        ),
    ]
