# Generated by Django 4.0.6 on 2022-09-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0007_alter_stagemanufacturingdetailinwork_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.detail', verbose_name='Деталь'),
        ),
    ]
