# Generated by Django 4.0.6 on 2022-12-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0007_alter_resolutionforstatementaboutjoboverdetail_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolutionforstatementaboutjoboverdetail',
            name='comment',
        ),
    ]
