# Generated by Django 4.0.6 on 2022-08-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0007_batchdetailinplan_comment_detailinplan_productinplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.product'),
        ),
    ]
