# Generated by Django 4.0.6 on 2022-09-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0008_alter_stagemanufacturingdetail_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='start_of_work',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
