# Generated by Django 4.0.6 on 2022-12-04 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0008_bonus_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdetailinplan',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_batch', to=settings.AUTH_USER_MODEL),
        ),
    ]
