# Generated by Django 4.0.6 on 2023-03-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0008_order_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemanufacturingdetail',
            name='class_work',
            field=models.CharField(blank=True, max_length=20, verbose_name='Разряд работы'),
        ),
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Описание'),
        ),
    ]
