# Generated by Django 4.0.6 on 2022-08-30 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0009_alter_workshopplan_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinplan',
            name='details',
        ),
        migrations.RemoveField(
            model_name='productinplan',
            name='name',
        ),
        migrations.AlterField(
            model_name='workshopplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop_data.product'),
        ),
        migrations.DeleteModel(
            name='DetailInPlan',
        ),
        migrations.DeleteModel(
            name='ProductInPlan',
        ),
    ]
