# Generated by Django 4.0.6 on 2022-09-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0009_alter_stagemanufacturingdetailinwork_start_of_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemanufacturingdetailinwork',
            name='in_work',
            field=models.BooleanField(default=True),
        ),
    ]
