# Generated by Django 4.0.6 on 2022-12-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0009_alter_resolutionforstatementaboutjoboverdetail_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionforstatementaboutjoboverdetail',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolute', to='workshop_data.statementaboutjoboverdetail'),
        ),
        migrations.AlterField(
            model_name='statementaboutjoboverdetail',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.detail', verbose_name='Деталь'),
        ),
    ]
