# Generated by Django 4.0.6 on 2023-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0009_stagemanufacturingdetail_class_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_number',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
