# Generated by Django 4.0.6 on 2022-08-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0010_remove_productinplan_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopplan',
            name='detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workshop_data.detail'),
            preserve_default=False,
        ),
    ]
