# Generated by Django 4.0.6 on 2022-12-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0010_alter_resolutionforstatementaboutjoboverdetail_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionforstatementaboutjoboverdetail',
            name='date_approval',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
