# Generated by Django 4.0.6 on 2023-03-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0010_product_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='order_number',
            new_name='order_number_commercial',
        ),
        migrations.AddField(
            model_name='product',
            name='order_number_state',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
