# Generated by Django 4.0.6 on 2022-09-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0010_stagemanufacturingdetailinwork_in_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='time_of_work',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
