# Generated by Django 4.0.6 on 2022-08-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0011_workshopplan_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopplan',
            name='quantity',
            field=models.SmallIntegerField(default=0, verbose_name='Колличество'),
        ),
        migrations.AddField(
            model_name='workshopplan',
            name='sos',
            field=models.BooleanField(default=False),
        ),
    ]
