# Generated by Django 4.0.6 on 2022-12-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0011_alter_resolutionforstatementaboutjoboverdetail_date_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='operations',
            field=models.CharField(max_length=300, unique=True, verbose_name='Операции'),
        ),
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Порядок'),
        ),
    ]
