# Generated by Django 4.0.6 on 2023-04-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0011_rename_order_number_product_order_number_commercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemanufacturingdetail',
            name='devation_card',
            field=models.CharField(blank=True, max_length=30, verbose_name='Карта отклонения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_number_commercial',
            field=models.SmallIntegerField(blank=True, verbose_name='Коммерция'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_number_state',
            field=models.SmallIntegerField(blank=True, verbose_name='Г/з'),
        ),
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='name',
            field=models.CharField(choices=[('', 'Выберите вид работы'), ('LSM', 'Слесарная'), ('TRN', 'Токарная'), ('MLR', 'Фрезеровочная'), ('GRN', 'Шлифовальная'), ('SLD', 'Пайка'), ('PRS', 'Пресс'), ('WLD', 'Сварка'), ('PRM', 'Програмная'), ('BRN', 'Прожиг'), ('HRM', 'Герметичка'), ('CTL', 'Контроль'), ('TML', 'Резьбо-фрезерная'), ('DVD', 'доводка-притирка')], max_length=3, verbose_name='Вид работы'),
        ),
    ]
