# Generated by Django 4.0.6 on 2022-09-25 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0011_alter_stagemanufacturingdetailinwork_time_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.batchdetailinplan', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='comment_in_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='in_work',
            field=models.BooleanField(default=True, verbose_name='В работе'),
        ),
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='stage_in_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.stagemanufacturingdetail', verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='time_of_work',
            field=models.SmallIntegerField(blank=True, verbose_name='Время'),
        ),
    ]
