# Generated by Django 4.0.6 on 2022-12-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0012_alter_stagemanufacturingdetail_operations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='workshop_data.batchdetailinplan', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='in_work',
            field=models.BooleanField(default=False, verbose_name='В работе'),
        ),
    ]
