# Generated by Django 4.0.6 on 2022-09-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0012_alter_stagemanufacturingdetailinwork_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='comment_in_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.comment', verbose_name='Комментарий'),
        ),
    ]
