# Generated by Django 4.0.6 on 2023-01-02 17:57

import django.core.validators
from django.db import migrations, models
import workshop_data.services.general_services


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0013_alter_stagemanufacturingdetailinwork_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Деталь'),
        ),
        migrations.AlterField(
            model_name='workshopplan',
            name='year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2022), workshop_data.services.general_services.max_value_current_year]),
        ),
    ]
