# Generated by Django 4.0.6 on 2022-09-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0013_alter_stagemanufacturingdetailinwork_comment_in_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='time_of_work',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Время'),
        ),
    ]
