# Generated by Django 4.0.6 on 2023-05-13 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0014_alter_workshopplan_in_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopplan',
            name='in_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.warehouse', verbose_name='в кладовой'),
        ),
    ]
