# Generated by Django 4.0.6 on 2022-09-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0014_alter_stagemanufacturingdetailinwork_time_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetailinwork',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='workshop_data.batchdetailinplan', verbose_name='Партия'),
        ),
    ]
