# Generated by Django 4.0.6 on 2023-01-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0014_alter_detail_name_alter_workshopplan_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagemanufacturingdetailinwork',
            name='time_of_work_stage',
        ),
    ]
