# Generated by Django 4.0.6 on 2022-10-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0015_alter_stagemanufacturingdetailinwork_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopplan',
            name='quantity',
        ),
        migrations.AddField(
            model_name='workshopplan',
            name='quantity_commercial_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Коммерция'),
        ),
        migrations.AddField(
            model_name='workshopplan',
            name='quantity_state_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Госзаказ'),
        ),
    ]
