# Generated by Django 4.0.6 on 2023-05-14 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0016_remove_workshopplan_in_warehouse_detail_in_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_warehouse', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='intermediate_detail',
            field=models.SmallIntegerField(default=0, verbose_name='Полуфабрикат'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='semis',
            field=models.SmallIntegerField(default=0, verbose_name='Заготовка'),
        ),
    ]
