# Generated by Django 4.0.6 on 2022-10-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0017_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopplan',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
