# Generated by Django 4.0.6 on 2023-05-14 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0017_warehouse_author_alter_warehouse_intermediate_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_warehouse', to=settings.AUTH_USER_MODEL),
        ),
    ]
