# Generated by Django 4.0.6 on 2023-05-14 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0018_alter_warehouse_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.comment', verbose_name='Комментарий'),
        ),
    ]
