# Generated by Django 4.0.6 on 2022-10-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0019_remove_workshopplan_ready_batchdetailinplan_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemanufacturingdetail',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='workshop_data.detail', verbose_name='Деталь'),
        ),
    ]
