# Generated by Django 4.0.6 on 2023-06-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0019_warehouse_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='workshopplan',
            name='comment',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.comment', verbose_name='Заметки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='section',
            field=models.SmallIntegerField(default=423, verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'штук'), (2, 'килограмм'), (3, 'не указан')], default=3, verbose_name='Единица измерения'),
        ),
    ]
