# Generated by Django 4.0.6 on 2022-10-16 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0020_alter_stagemanufacturingdetail_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchdetailinplan',
            name='detail',
        ),
        migrations.AddField(
            model_name='batchdetailinplan',
            name='workshopplan_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batchs', to='workshop_data.workshopplan'),
        ),
    ]
