# Generated by Django 4.0.6 on 2023-08-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0020_alter_product_options_workshopplan_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'январь'), (2, 'февраль'), (3, 'март'), (4, 'апрель'), (5, 'май'), (6, 'июнь'), (7, 'июль'), (8, 'август'), (9, 'сентябрь'), (10, 'октябрь'), (11, 'ноябрь'), (12, 'декабрь'), (13, 'не указан')], default=13, verbose_name='Месяц')),
                ('first_side_time', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Время 1я сторона')),
                ('second_side_time', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Время 2я сторона')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Расценка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_job_spy', to=settings.AUTH_USER_MODEL)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.detail', verbose_name='Деталь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop_data.product', verbose_name='Изделие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_job', to=settings.AUTH_USER_MODEL, verbose_name='Рабочий')),
            ],
        ),
    ]
