# Generated by Django 4.0.6 on 2023-08-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0021_recordjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordjob',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
