# Generated by Django 4.0.6 on 2023-08-20 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0022_recordjob_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametersDetailForSPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operations_first_side', models.TextField(blank=True, verbose_name='Операции 1й стороны')),
                ('operations_second_side', models.TextField(blank=True, verbose_name='Операции 2й стороны')),
                ('first_side_time', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Время 1я сторона')),
                ('second_side_time', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Время 2я сторона')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Расценка')),
            ],
        ),
        migrations.RemoveField(
            model_name='recordjob',
            name='first_side_time',
        ),
        migrations.RemoveField(
            model_name='recordjob',
            name='price',
        ),
        migrations.RemoveField(
            model_name='recordjob',
            name='second_side_time',
        ),
        migrations.AddField(
            model_name='detail',
            name='parameters_for_spu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop_data.parametersdetailforspu'),
        ),
    ]
