# Generated by Django 4.0.6 on 2023-08-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0023_parametersdetailforspu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordjob',
            name='quantity',
        ),
        migrations.AddField(
            model_name='recordjob',
            name='quantity_1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество по 1й стороне'),
        ),
        migrations.AddField(
            model_name='recordjob',
            name='quantity_2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество по 2й стороне'),
        ),
    ]
