# Generated by Django 4.0.6 on 2023-08-22 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0024_remove_recordjob_quantity_recordjob_quantity_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersdetailforspu',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_parameter_detail_cpu', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='first_side_time',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Время 1я сторона'),
        ),
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='operations_first_side',
            field=models.TextField(blank=True, null=True, verbose_name='Операции 1й стороны'),
        ),
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='operations_second_side',
            field=models.TextField(blank=True, null=True, verbose_name='Операции 2й стороны'),
        ),
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Расценка'),
        ),
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='second_side_time',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Время 2я сторона'),
        ),
    ]
