# Generated by Django 4.0.6 on 2023-08-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0026_alter_parametersdetailforspu_first_side_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='parameters_for_spu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop_data.parametersdetailforspu'),
        ),
    ]
