# Generated by Django 4.0.6 on 2023-08-24 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0027_alter_detail_parameters_for_spu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_parameter_detail_cpu', to=settings.AUTH_USER_MODEL),
        ),
    ]
