# Generated by Django 4.0.6 on 2023-08-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0029_alter_detail_parameters_for_spu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Расценка'),
        ),
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='second_side_time',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Время 2я сторона'),
        ),
    ]
