# Generated by Django 4.0.6 on 2023-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0030_alter_parametersdetailforspu_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='first_side_time',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Время 1я сторона'),
        ),
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Расценка'),
        ),
    ]
