# Generated by Django 4.0.6 on 2023-08-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0031_alter_parametersdetailforspu_first_side_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersdetailforspu',
            name='norm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Норма время'),
        ),
    ]
