# Generated by Django 4.0.6 on 2023-08-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0033_alter_parametersdetailforspu_first_side_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordjob',
            name='quantity_1',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество по 1й стороне'),
        ),
        migrations.AlterField(
            model_name='recordjob',
            name='quantity_2',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество по 2й стороне'),
        ),
    ]
