# Generated by Django 4.0.6 on 2023-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0035_alter_recordjob_quantity_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersdetailforspu',
            name='coefficient_first_side',
            field=models.FloatField(blank=True, default=1, verbose_name='Коэффициент 1'),
        ),
        migrations.AddField(
            model_name='parametersdetailforspu',
            name='coefficient_second_side',
            field=models.FloatField(blank=True, default=1, verbose_name='Коэффициент 2'),
        ),
    ]
