# Generated by Django 4.0.6 on 2023-08-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0037_alter_parametersdetailforspu_first_side_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='coefficient_first_side',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Коэффициент 1'),
        ),
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='coefficient_second_side',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Коэффициент 2'),
        ),
    ]
