# Generated by Django 4.0.6 on 2023-09-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0038_alter_parametersdetailforspu_coefficient_first_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordjob',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество по двум сторонам'),
        ),
    ]
