# Generated by Django 4.0.6 on 2023-09-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0039_recordjob_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordjob',
            name='order_at_master',
            field=models.BooleanField(default=False, verbose_name='Наряд сдан'),
        ),
        migrations.AddField(
            model_name='recordjob',
            name='order_yes',
            field=models.BooleanField(default=False, verbose_name='Наряд выписан'),
        ),
    ]
