# Generated by Django 4.0.6 on 2023-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0040_recordjob_order_at_master_recordjob_order_yes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordjob',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество по двум сторонам'),
        ),
        migrations.AlterField(
            model_name='recordjob',
            name='quantity_1',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество по 1й стороне'),
        ),
        migrations.AlterField(
            model_name='recordjob',
            name='quantity_2',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество по 2й стороне'),
        ),
    ]
