# Generated by Django 4.0.6 on 2023-10-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0041_alter_recordjob_quantity_alter_recordjob_quantity_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MillingDetailForSPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(blank=True, default=0)),
                ('norm_milling', models.FloatField(blank=True, default=0)),
                ('price', models.FloatField(blank=True, default=0)),
                ('operations', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='parametersdetailforspu',
            name='milling_operations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.millingdetailforspu'),
        ),
    ]
