# Generated by Django 4.0.6 on 2023-10-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0043_recordjob_milling_was'),
    ]

    operations = [
        migrations.AddField(
            model_name='millingdetailforspu',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.comment'),
        ),
    ]
