# Generated by Django 4.0.6 on 2023-10-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0044_millingdetailforspu_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersdetailforspu',
            name='milling_operations',
        ),
        migrations.AddField(
            model_name='millingdetailforspu',
            name='milling_for_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.detail'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='parameters_for_spu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.parametersdetailforspu'),
        ),
    ]
