# Generated by Django 4.0.6 on 2023-10-15 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_data', '0045_remove_parametersdetailforspu_milling_operations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='millingdetailforspu',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='author_milling_spu', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
