# Generated by Django 4.0.6 on 2023-10-23 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0047_remove_millingdetailforspu_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millingdetailforspu',
            name='milling_for_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milling_in_detail', to='workshop_data.detail'),
        ),
    ]
