# Generated by Django 4.0.6 on 2023-10-29 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0048_alter_millingdetailforspu_milling_for_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersdetailforspu',
            name='difficultly',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
    ]
