# Generated by Django 4.0.6 on 2023-11-12 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0049_parametersdetailforspu_difficultly'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordjob',
            name='green_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Время работы станка в зеленом режиме'),
        ),
        migrations.AddField(
            model_name='recordjob',
            name='work_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Время работы оператора за станком'),
        ),
        migrations.AlterField(
            model_name='parametersdetailforspu',
            name='difficultly',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)], verbose_name='Сложность'),
        ),
    ]
