# Generated by Django 4.0.6 on 2023-12-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0051_remove_recordjob_green_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationoftheoperatorswork',
            name='barfider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluationoftheoperatorswork',
            name='machine',
            field=models.CharField(choices=[('001', 'Смек 1'), ('002', 'Смек 2 барфидер'), ('003', 'Смек 3'), ('004', 'Смек 4 барфидер'), ('005', 'Шпинер 1'), ('006', 'Шпинер 2'), ('007', 'Малыш')], default=1, max_length=3, verbose_name='Станок'),
            preserve_default=False,
        ),
    ]
