# Generated by Django 4.0.6 on 2023-12-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0053_evaluationoftheoperatorswork_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationoftheoperatorswork',
            name='coefficient_for_date',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
