# Generated by Django 4.0.6 on 2023-12-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0055_alter_evaluationoftheoperatorswork_coefficient_for_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationoftheoperatorswork',
            old_name='coefficient_for_date',
            new_name='coefficient_for_day',
        ),
    ]
