# Generated by Django 4.0.6 on 2022-12-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
