# Generated by Django 4.0.6 on 2023-02-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_remove_user_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('LSM', 'Слесарь'), ('TRN', 'Токарь'), ('MLR', 'Фрезеровщик'), ('MSR', 'Мастер'), ('EPB', 'Инженер ПДБ'), ('SLR', 'Пайщик'), ('WLR', 'Сварщик')], max_length=3),
        ),
    ]
