# Generated by Django 4.0.6 on 2023-03-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(verbose_name='День Рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.IntegerField(verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_rank',
            field=models.IntegerField(default=3, verbose_name='Разряд рабочего'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MN', 'Мужчина'), ('WN', 'Женщина')], default='MN', max_length=2, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=70, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('866', 'Слесарь'), ('914', 'Токарь'), ('944', 'Фрезеровщик'), ('MSR', 'Мастер'), ('EPB', 'Инженер ПДБ'), ('916', 'Пайщик'), ('WLR', 'Сварщик'), ('961', 'Шлифовщик'), ('773', 'Оператор ЧПУ'), ('601', 'Испытатель')], max_length=3, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=70, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True, verbose_name='Логин'),
        ),
    ]
