# Generated by Django 4.0.6 on 2023-03-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0007_alter_user_birthday_alter_user_employee_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('866', 'Слесарь'), ('914', 'Токарь'), ('944', 'Фрезеровщик'), ('MSR', 'Мастер'), ('EPB', 'Инженер ПДБ'), ('916', 'Пайщик'), ('892', 'Сварщик'), ('961', 'Шлифовщик'), ('773', 'Оператор ЧПУ'), ('601', 'Испытатель')], max_length=3, verbose_name='Профессия'),
        ),
    ]
