# Generated by Django 4.0.6 on 2023-03-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0008_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.IntegerField(blank=True, default=1, verbose_name='Участок'),
        ),
    ]
