# Generated by Django 4.0.6 on 2023-10-29 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_data', '0048_alter_millingdetailforspu_milling_for_detail'),
        ('sign', '0009_user_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingAtTheMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('machine', models.CharField(choices=[('001', 'Смек 1'), ('002', 'Смек 2 барфидер'), ('003', 'Смек 3'), ('004', 'Смек 4 барфидер'), ('005', 'Шпинер 1'), ('006', 'Шпинер 2'), ('007', 'Малыш')], max_length=3, verbose_name='Станок')),
                ('work_time_green', models.FloatField(blank=True, default=0, null=True)),
                ('barfider', models.BooleanField(default=False)),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_data.detail')),
            ],
        ),
    ]
