# Generated by Django 4.0.6 on 2023-11-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0010_workingatthemachine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkingAtTheMachine',
        ),
    ]
