# Generated by Django 4.0.6 on 2023-12-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0011_delete_workingatthemachine'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_coefficient_operator',
            field=models.FloatField(default=0),
        ),
    ]
